### ISSUE TITLE
Question : how to use in gridsome

### ISSUE THREAD

**Issue by slfhstr** [avatarbabe/gridsome-source-directus9#1]
Looks nice plugin !
Not so familiar with Gridsome, so excuse me asking how would you deploy/integrate in Gridsome ?
Just some basic example

**Comment by avatarbabe** [comment]
Hello, I updated the readme to help you out :) Last update for this was for Directus rc34, and latest is rc57. Let me know if it doesn't work with the latest Directus version and I'll fix it

**Comment by slfhstr** [comment]
Thank you so much !
